# ベースイメージ
FROM node:18.13.0 as builder
WORKDIR /usr/src/app

# 依存関係のインストール
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install

# アプリケーションコードのコピー
COPY . .

# アプリケーションのビルド
RUN yarn build

# 本番用のベースイメージ
FROM node:18.13.0
WORKDIR /usr/src/app

# 依存関係のインストール（本番用）
COPY --from=builder /usr/src/app/package.json /usr/src/app/yarn.lock ./
RUN yarn install --production

# ビルドされたファイルのコピー
COPY --from=builder /usr/src/app/dist ./dist

# 環境変数の設定
ENV NODE_ENV=production
ENV TODOAPP_ENV=production

# 本番用の起動コマンド
CMD ["dist/src/main.js"]