name: 'todoapp-server deploy'
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile_todoapp_conoha
          push: true
          tags: ${{secrets.DOCKER_USER_NAME}}/todoapp-server:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
      - name: run scripts
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{secrets.SSH_HOST}}
          USERNAME: ${{secrets.SSH_USERNAME}}
          PORT: ${{secrets.SSH_PORT}}
        run: sh .github/workflows/deploy.sh